In [2]:
import numpy as np
a=[1,2,3,4]
b=[5,6,7,8]
a+b   
[a[i] + b[i] for i in range(len(a))]


[6, 8, 10, 12]

In [3]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr[2:]

array([[7, 8, 9]])

In [ ]:
arr[1:,1:]  #start_row:end_row, start_col:end_col

array([[5, 6],
       [8, 9]])

In [6]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [7]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [10]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a[a>2]

array([3, 4])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
a=np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [17]:
a=np.array([1,2,3,4])
a*2

array([2, 4, 6, 8])

In [18]:
np.dot(a,b)


np.int64(70)

In [20]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [21]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [24]:
a=np.array([[1,2],[3,4]])
b=np.array([1,2,3])
a,b

(array([[1, 2],
        [3, 4]]),
 array([1, 2, 3]))

In [27]:
np.linalg.inv(a)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [30]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [31]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [33]:
np.sum(a,axis=0)

array([4, 6])

In [34]:
np.sum(a,axis=1)

array([3, 7])

In [36]:
def mean(array):
    n=len(array)
    return np.sum(array)/n
mean(np.array([1,2,3,4,5]))

np.float64(3.0)

In [40]:
def variance(array):
    n=len(array)
    m=mean(array)
    return np.sum((array-m)**2)/n  
variance(np.array([1,2,3,4,5]))  

np.float64(2.0)